@baseUrl = http://localhost:8080
@contentType = application/json


//login into the system as admin and get the tokens
//check if the protected endpoints are accessible with the access token
//check if the refresh token endpoint works and get new access token and refresh token
//check if the protected endpoints are accessible with the new access token
//check if the old access token still works (it should not) with the protected endpoints
//logout and try to access protected endpoints (should fail)


### ===================================
### TEST LOGIN TO GET TOKENS
### ===================================
POST {{baseUrl}}/api/login
Content-Type: {{contentType}}

{
  "username": "admin",
  "password": "admin"
}

###result after successful login - got access token and refresh token

### ===================================
### STEP 2: TEST PROTECTED ENDPOINTS
### ===================================

GET {{baseUrl}}/api/protected-message-admin
Authorization: Bearer

### ===================================
### Test refresh token endpoint
### ===================================
POST {{baseUrl}}/api/refresh-token
Content-Type: {{contentType}}

{
    "refreshToken": ""
}


### ===================================
### Test LOGOUT
### ===================================
POST {{baseUrl}}/api/logout
Content-Type: {{contentType}}
Authorization: Bearer